name: Build and deploy app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/iron
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: |
          git checkout -b dist
      - run: |
          mkdir temp-dist
          mv dist/* temp-dist/ || true
          git rm -r dist
          mv temp-dist/* .
          git add -A
          rm -r temp-dist
      - run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "rebuild: ${timestamp}" || exit 0
          git push origin dist
